services:
  - type: web
    name: healthify
    env: python
    plan: free
    buildCommand: |
      echo "python-3.10.13" > runtime.txt
      pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
